version: 0.0
os: linux

# 코드 파일 전송과 관련된 설정
files:
  - source: /
    destination: /home/ec2-user/app/deploy
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user